accounts/urls.py
from django.urls import path, include

from accounts.views import (
    SignUpView,
    ActivateAccountView,
    PreLogoutView,
    UserDetailView,
    UserUpdateView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
)

app_name = "accounts"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup/", SignUpView.as_view(), name="sign-up"),
    path("user/update/", UserUpdateView.as_view(), name="user-update"),
    path(
        "password/change/", CustomPasswordChangeView.as_view(), name="password-change"
    ),
    path(
        "password/change/done/",
        CustomPasswordChangeDoneView.as_view(),
        name="password-change-done",
    ),
    path("pre-logout/", PreLogoutView.as_view(), name="pre-logout"),
    path(
        "activate/<str:uid>/<str:token>/",
        ActivateAccountView.as_view(),
        name="activate",
    ),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("flowdesk.urls", namespace="flowdesk")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flowdesk/urls.py
from django.urls import path

from flowdesk.views import (
    IndexView,
    WorkspaceDetailView,
    WorkspaceMembersView,
    WorkspaceTagsView,
    WorkspaceCreateView,
    WorkspaceUpdateView,
    WorkspaceDeleteView,
    WorkspaceInviteView,
    WorkspaceJoinView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    BoardDetailView,
    BoardCreateView,
    BoardUpdateView,
    BoardDeleteView,
    ListCreateView,
    ListUpdateView,
    ListDeleteView,
    ListOrderUpdate,
    TaskDetailView,
    TaskGraphView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskOrderUpdate,
    CommentCreateView,
)

app_name = "flowdesk"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "workspaces/<int:pk>/", WorkspaceDetailView.as_view(), name="workspace-detail"
    ),
    path(
        "workspaces/<int:pk>/members/",
        WorkspaceMembersView.as_view(),
        name="workspace-members",
    ),
    path(
        "workspaces/<int:pk>/tags/",
        WorkspaceTagsView.as_view(),
        name="workspace-tags",
    ),
    path("workspaces/create/", WorkspaceCreateView.as_view(), name="workspace-create"),
    path(
        "workspaces/<int:pk>/update/",
        WorkspaceUpdateView.as_view(),
        name="workspace-update",
    ),
    path(
        "workspaces/<int:pk>/delete/",
        WorkspaceDeleteView.as_view(),
        name="workspace-delete",
    ),
    path(
        "workspaces/<int:pk>/invite/",
        WorkspaceInviteView.as_view(),
        name="workspace-invite",
    ),
    path(
        "workspaces/<int:pk>/join/<uidb64>/<token>/",
        WorkspaceJoinView.as_view(),
        name="workspace-join",
    ),
    path(
        "workspaces/<int:workspace_pk>/tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "workspaces/<int:workspace_pk>tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "workspaces/<int:workspace_pk>tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/create/",
        BoardCreateView.as_view(),
        name="board-create",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:pk>/update/",
        BoardUpdateView.as_view(),
        name="board-update",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:pk>/delete/",
        BoardDeleteView.as_view(),
        name="board-delete",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:pk>/",
        BoardDetailView.as_view(),
        name="board-detail",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/create/",
        ListCreateView.as_view(),
        name="list-create",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:pk>/update/",
        ListUpdateView.as_view(),
        name="list-update",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:pk>/delete/",
        ListDeleteView.as_view(),
        name="list-delete",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/order/",
        ListOrderUpdate.as_view(),
        name="update-list-order",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/<int:pk>/graph",
        TaskGraphView.as_view(),
        name="task-graph",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/tasks/order/",
        TaskOrderUpdate.as_view(),
        name="update-task-order",
    ),
    path(
        "workspaces/<int:workspace_pk>/boards/<int:board_pk>/lists/<int:list_pk>/tasks/<int:task_pk>/comments/create/",
        CommentCreateView.as_view(),
        name="comment-create",
    ),
]

templates/includes/sidebar.html
<div id="sidebar" class="d-flex flex-column flex-shrink-0 p-3">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
    <span class="sidebar-title">Flowdesk</span>
  </a>
  <hr style="border-color: #343a40;">

  <ul class="list-unstyled ps-0">
    <li class="mb-1">
      <button class="btn btn-toggle align-items-center rounded collapsed" 
          data-bs-toggle="collapse" 
          data-bs-target="#account-collapse" 
          aria-expanded="false">
        <i class="bi bi-person-circle"></i>
        <span>Account</span>
      </button>
      <div class="collapse" id="account-collapse">
        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          {% if request.user.is_authenticated %}
            <li><a href="{% url 'accounts:user-detail' request.user.pk %}" class="">Profile</a></li>
            <li><a href="{% url 'accounts:user-update' %}" class="">Settings</a></li>
            <li><a href="{% url 'accounts:pre-logout' %}" class="">Logout</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}" class="">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </li>

    {% if request.user.is_authenticated %}
      <hr style="border-color: #343a40;">

      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded disabled w-100 text-start">
          Workspaces
        </button>
      </li>

      {% for ws in user_workspaces %}
        <li class="mb-1">
          <button class="btn btn-toggle align-items-center rounded collapsed w-100 text-start" 
                  data-bs-toggle="collapse" 
                  data-bs-target="#workspace-{{ ws.id }}-collapse" 
                  aria-expanded="false">
            <i class="bi bi-box-seam"></i>
            <span>{{ ws.name }}</span>
          </button>
          <div class="collapse" id="workspace-{{ ws.id }}-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
              <li><a href="{% url 'flowdesk:workspace-detail' ws.pk %}" class="">
                <i class="bi bi-kanban"></i>
                <span>Boards</span>
              </a></li>
              <li><a href="{% url 'flowdesk:workspace-members' ws.pk %}" class="">
                <i class="bi bi-people"></i>
                <span>Members</span>
              </a></li>
              <li><a href="{% url 'flowdesk:workspace-tags' ws.pk %}" class="">
                <i class="bi bi-bookmarks"></i>
                <span>Task tags</span>
              </a></li>
              <li><a href="{% url 'flowdesk:workspace-update' ws.pk %}" class="">
                <i class="bi bi-gear"></i>
                <span>Settings</span>
              </a></li>
            </ul>
          </div>
        </li>
      {% endfor %}

      <li class="mb-1">
        <a href="{% url 'flowdesk:workspace-create' %}" 
           class="btn btn-secondary align-items-center rounded w-100 text-start">
          + Create Workspace
        </a>
      </li>
    {% endif %}
  </ul>
</div>